Update license to .NET Foundation standard and handle CRLF correctly
dnnsoftware/Language-Pack-DE-DE pull request #4
Opened 2020-06-05 08:02 UTC by EPTamminga

Close #3

2020-06-05 14:26 UTC, bdukes approved these changes

2020-06-06 01:36 UTC, sleupold commented
I'd prefer to update it with the next LP update.

2020-06-06 01:36 UTC, sleupold requested changes
I'd prefer to update it with the next LP update.

2020-06-08 18:38 UTC, valadas commented
@sleupold what do you mean, this is for the next release right?

2026-01-29 22:08 UTC, valadas commented
Done in #5

2026-01-29 22:08 UTC, closed without merging